name: on_push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  security-events: write

jobs:

  test:
    name: Test Code
    runs-on: ubuntu-latest
    env:
      GO_VERSION: '1.25'
      LINTER_VERSION: '1.53.3'
      GOLANGCI_LINT_VERSION: v2.6
      SCAN_SEVERITY: 'MEDIUM'
    steps:

      # Setup Environment
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00  # v6.0.0
        with:
          go-version: '${{ env.GO_VERSION }}'
          cache: true
          cache-dependency-path: 'go.sum'
          check-latest: true

      # Unit Tests
      - name: Tidy Modules
        run: make tidy
      - name: Run Tests with Coverage
        run: make test
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de  # v5.5.2
        with:
          files: ./coverage.out
          verbose: true
          use_oidc: true
        continue-on-error: true

      # Lint Code
      - name: Config Go Lint
        id: golangci_config
        uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6  # v3.0.0
        with:
          files: .golangci.yaml
      - name: Lint Go
        if: steps.golangci_config.outputs.files_exists == 'true'
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20  # v9.2.0
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --timeout=5m
          only-new-issues: ${{ github.event_name == 'pull_request' }}
          skip-cache: false
      - name: Config YAML Lint
        id: yamllint_config
        uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6  # v3.0.0
        with:
          files: .yamllint.yaml
      - name: Lint YAML
        if: steps.yamllint_config.outputs.files_exists == 'true'
        uses: karancode/yamllint-github-action@4052d365f09b8d34eb552c363d1141fd60e2aeb2  # v3.0.0
        with:
          yamllint_config_filepath: .yamllint.yaml

      # Scan for Vulnerabilities
      - name: Run Trivy Security Scan
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8  # v0.33.1
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          hide-progress: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: ${{ env.SCAN_SEVERITY }}
          exit-code: '1'
      - name: Upload Trivy Results to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@16df4fbc19aea13d921737861d6c622bf3cefe23  # v2.23.0
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'trivy-fs'