name: on_tag
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'  # Only build tag with semantic versioning format

permissions:
  attestations: write
  contents: write
  id-token: write
  packages: write

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GO_VERSION: '1.25'
      GOLANGCI_LINT_VERSION: v2.6
      CRANE_VERSION: 'v0.20.6'
      IDENTITY_PROVIDER: 'projects/116689922666/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
      PROJECT_ID: 'eidosx'
      SERVICE_ACCOUNT: 'github-actions-user'
      RUN_REGION: 'us-west1'
      RUN_SERVICE: 'api'
      RUN_IMAGE_REG: 'us-docker.pkg.dev/eidosx/ghcr/mchmarny'
    steps:

      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      # Setup, Test, and Lint
      - name: Run Go CI (setup, test, lint)
        uses: ./.github/actions/go-ci
        with:
          go_version: '${{ env.GO_VERSION }}'
          golangci_lint_version: '${{ env.GOLANGCI_LINT_VERSION }}'
          upload_codecov: 'false'

      # Build and Release
      - name: Build and Release
        id: release
        uses: ./.github/actions/go-build-release

      - name: Attest cnsd image
        uses: ./.github/actions/attest-image-from-tag
        with:
          image_name: ghcr.io/${{ github.repository_owner }}/cnsd
          tag: ${{ github.ref_name }}
          crane_version: ${{ env.CRANE_VERSION }}

      - name: Attest cnsctl image
        uses: ./.github/actions/attest-image-from-tag
        with:
          image_name: ghcr.io/${{ github.repository_owner }}/cns
          tag: ${{ github.ref_name }}
          crane_version: ${{ env.CRANE_VERSION }}

      # Deploy to Cloud Run
      - name: Deploy API to Cloud Run
        if: steps.release.outputs.release_outcome == 'success'
        uses: ./.github/actions/cloud-run-deploy
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.IDENTITY_PROVIDER }}
          service_account: "${{ env.SERVICE_ACCOUNT }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com"
          region: ${{ env.RUN_REGION }}
          service: ${{ env.RUN_SERVICE }}
          image: "${{ env.RUN_IMAGE_REG }}/cnsd:${{ github.ref_name }}"