# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: on_tag
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'  # Only build tag with semantic versioning format

permissions:
  attestations: write
  contents: write
  id-token: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GO_VERSION: '1.25'
      GOLANGCI_LINT_VERSION: v2.6
      ADDLICENSE_VERSION: v1.1.1
      CRANE_VERSION: 'v0.20.6'
      IDENTITY_PROVIDER: 'projects/116689922666/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
      PROJECT_ID: 'eidosx'
      SERVICE_ACCOUNT: 'github-actions-user'
      RUN_REGION: 'us-west1'
      RUN_SERVICE: 'api'
      RUN_IMAGE_REG: 'us-docker.pkg.dev/eidosx/ghcr/mchmarny'
    steps:

      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      # Setup, Test, and Lint
      - name: Run Go CI (setup, test, lint)
        uses: ./.github/actions/go-ci
        with:
          go_version: '${{ env.GO_VERSION }}'
          golangci_lint_version: '${{ env.GOLANGCI_LINT_VERSION }}'
          addlicense_version: '${{ env.ADDLICENSE_VERSION }}'
          upload_codecov: 'false'

      # Build and Release
      - name: Build and Release
        id: release
        uses: ./.github/actions/go-build-release
        with:
          homebrew_tap_token: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}

      - name: Attest cnsd image
        uses: ./.github/actions/attest-image-from-tag
        with:
          image_name: ghcr.io/${{ github.repository_owner }}/cnsd
          tag: ${{ github.ref_name }}
          crane_version: ${{ env.CRANE_VERSION }}

      - name: Attest cnsctl image
        uses: ./.github/actions/attest-image-from-tag
        with:
          image_name: ghcr.io/${{ github.repository_owner }}/cns
          tag: ${{ github.ref_name }}
          crane_version: ${{ env.CRANE_VERSION }}

      # Deploy to Cloud Run
      - name: Deploy API to Cloud Run
        if: steps.release.outputs.release_outcome == 'success'
        uses: ./.github/actions/cloud-run-deploy
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.IDENTITY_PROVIDER }}
          service_account: "${{ env.SERVICE_ACCOUNT }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com"
          region: ${{ env.RUN_REGION }}
          service: ${{ env.RUN_SERVICE }}
          image: "${{ env.RUN_IMAGE_REG }}/cnsd:${{ github.ref_name }}"